var httpStatus = {
	100: { message: "Continue", detail: "" },
	101: { message: "Switching Protocols", detail: "" },
	102: { message: "Processing", detail: "" },

	200: { message: "OK", detail: "" },
	201: { message: "Created", detail: "" },
	202: { message: "Accepted", detail: "" },
	203: { message: "Non-Authoritative Information", detail: "since HTTP/1.1" },
	204: { message: "No Content", detail: "" },
	205: { message: "Reset Content", detail: "" },
	206: { message: "Partial Content", detail: "" },
	207: { message: "Multi-Status", detail: "WebDAV; RFC 4918" },
	208: { message: "Already Reported", detail: "WebDAV; RFC 5842" },
	226: { message: "IM Used", detail: "RFC 3229" },

	300: { message: "Multiple Choices", detail: "" },
	301: { message: "Moved Permanently", detail: "" },
	302: { message: "Found", detail: "" },
	303: { message: "See Other", detail: "since HTTP/1.1" },
	304: { message: "Not Modified", detail: "" },
	305: { message: "Use Proxy", detail: "since HTTP/1.1" },
	306: { message: "Switch Proxy", detail: "" },
	307: { message: "Temporary Redirect", detail: "since HTTP/1.1" },
	308: { message: "Permanent Redirect", detail: "Experimental RFC; RFC 7238" },

	400: { message: "Bad Request", detail: "" },
	401: { message: "Unauthorized", detail: "" },
	402: { message: "Payment Required", detail: "" },
	403: { message: "Forbidden", detail: "" },
	404: { message: "Not Found", detail: "" },
	405: { message: "Method Not Allowed", detail: "" },
	406: { message: "Not Acceptable", detail: "" },
	407: { message: "Proxy Authentication Required", detail: "" },
	408: { message: "Request Timeout", detail: "" },
	409: { message: "Conflict", detail: "" },
	410: { message: "Gone", detail: "" },
	411: { message: "Length Required", detail: "" },
	412: { message: "Precondition Failed", detail: "" },
	413: { message: "Request Entity Too Large", detail: "" },
	414: { message: "Request-URI Too Long", detail: "" },
	415: { message: "Unsupported Media Type", detail: "" },
	416: { message: "Requested Range Not Satisfiable", detail: "" },
	417: { message: "Expectation Failed", detail: "" },
	418: { message: "I'm a teapot", detail: "RFC 2324" },
	419: { message: "Authentication Timeout", detail: "not in RFC 2616" },
	420: { message: "Method Failure || Enhance Your Calm", detail: "Spring Framework || Twitter" },
	422: { message: "Unprocessable Entity", detail: "WebDAV; RFC 4918" },
	423: { message: "Locked", detail: "WebDAV; RFC 4918" },
	424: { message: "Failed Dependency", detail: "WebDAV; RFC 4918" },
	426: { message: "Upgrade Required", detail: "" },
	428: { message: "Precondition Required", detail: "RFC 6585" },
	429: { message: "Too Many Requests", detail: "RFC 6585" },
	431: { message: "Request Header Fields Too Large", detail: "RFC 6585" },
	440: { message: "Login Timeout", detail: "Microsoft" },
	444: { message: "No Response", detail: "Nginx" },
	449: { message: "Retry With", detail: "Microsoft" },
	450: { message: "Blocked by Windows Parental Controls", detail: "Microsoft" },
	451: { message: "Unavailable For Legal Reasons || Redirect", detail: "Internet draft || Microsoft" },
	494: { message: "Request Header Too Large", detail: "Nginx" },
	495: { message: "Cert Error", detail: "Nginx" },
	496: { message: "No Cert", detail: "Nginx" },
	497: { message: "HTTP to HTTPS", detail: "Nginx" },
	498: { message: "Token expired/invalid", detail: "Esri" },
	499: { message: "Client Closed Request || Token required", detail: "Nginx || Esri" },

	500: { message: "Internal Server Error", detail: "" },
	501: { message: "Not Implemented", detail: "" },
	502: { message: "Bad Gateway", detail: "" },
	503: { message: "Service Unavailable", detail: "" },
	504: { message: "Gateway Timeout", detail: "" },
	505: { message: "HTTP Version Not Supported", detail: "" },
	506: { message: "Variant Also Negotiates", detail: "RFC 2295" },
	507: { message: "Insufficient Storage", detail: "WebDAV; RFC 4918" },
	508: { message: "Loop Detected", detail: "WebDAV; RFC 5842" },
	509: { message: "Bandwidth Limit Exceeded", detail: "Apache bw/limited extension" },
	510: { message: "Not Extended", detail: "RFC 2774" },
	511: { message: "Network Authentication", detail: "Required (RFC 6585)" },
	520: { message: "Origin Error", detail: "Cloudflare" },
	521: { message: "Web server is down", detail: "Cloudflare" },
	522: { message: "Connection timed out", detail: "Cloudflare" },
	523: { message: "Proxy Declined Request", detail: "Cloudflare" },
	524: { message: "A timeout occurred", detail: "Cloudflare" },
	598: { message: "Network read timeout error", detail: "Unknown" },
	599: { message: "Network connect timeout error", detail: "Unknown" },

	"unknown": { message: "Unknown http status code was received", detail: "" }
}

module.exports = httpStatus;
