/* automatically generated by ./DiskIO/modules.sh AIO Blocking DiskDaemon DiskThreads IpcIo Mmapped
 * do not edit
 */
#include "squid.h"
#include "DiskIO/DiskIOModule.h"
#include "DiskIO/AIO/AIODiskIOModule.h"
#include "DiskIO/Blocking/BlockingDiskIOModule.h"
#include "DiskIO/DiskDaemon/DiskDaemonDiskIOModule.h"
#include "DiskIO/DiskThreads/DiskThreadsDiskIOModule.h"
#include "DiskIO/IpcIo/IpcIoDiskIOModule.h"
#include "DiskIO/Mmapped/MmappedDiskIOModule.h"

void DiskIOModule::PokeAllModules(void)
{
    AIODiskIOModule::GetInstance();
    BlockingDiskIOModule::GetInstance();
    DiskDaemonDiskIOModule::GetInstance();
    DiskThreadsDiskIOModule::GetInstance();
    IpcIoDiskIOModule::GetInstance();
    MmappedDiskIOModule::GetInstance();
}
