#!/bin/sh
# Monitor log file sizes. Allow the sizes to be one megabyte.
# Spaceify Oy 7.7.2016

limit_size ()
{
	if [ -f $1 ]; then

		actualsize=$(wc -c < $1)

		if [ $actualsize -gt 1048576 ]; then
			cp $1 "$1.1" > /dev/null 2>&1 || true
			printf "" > $1
		fi

	fi
} 

logPath="/var/lib/spaceify/data/logs/"

limit_size "${logPath}spaceify.log"
#limit_size "${logPath}spaceifyappman.log"
#limit_size "${logPath}spaceifydns.log"
#limit_size "${logPath}spaceifyhttp.log"
#limit_size "${logPath}spaceifyitp.log"
