#!/bin/bash
# Bash TAB key completion script for Spaceify's spm command
# Spaceify Oy 5.5.2015
# Location: /etc/bash_completion.d/

_default ()																		# For displaying default possibilities
{
	local param
	param="$1"
	COMPREPLY=( $( compgen -W "$param" -- $cur ) )
}

_spm ()
{
	#compopt -o default;
	local cur																	# Pointer to current completion word.
	COMPREPLY=()																# Array variable storing the possible completions.
	cur=${COMP_WORDS[COMP_CWORD]}

	is_command=true; if [ ${#COMP_WORDS[@]} -ge 3 ] && [ $COMP_CWORD -ne 1 ]; then is_command=false; fi

	if [ "$is_command" == true ]; then											# Complete commands
		case "$cur" in
			i*) COMPREPLY=( $( compgen -W 'install' $cur ) ) ;;
			p*) COMPREPLY=( $( compgen -W 'publish' $cur ) ) ;;
			r*) COMPREPLY=( $( compgen -W 'remove restart register' $cur ) ) ;;
			s*) COMPREPLY=( $( compgen -W 'source start stop states' $cur ) ) ;;
			l*) COMPREPLY=( $( compgen -W 'list' $cur ) ) ;;
			h*) COMPREPLY=( $( compgen -W 'help' $cur ) ) ;;
			v*) COMPREPLY=( $( compgen -W 'version' $cur ) ) ;;
			 *) _default "install publish remove restart register source start states stop list help version" ;;
		esac
	else																		# Complete options for commands
		command=${COMP_WORDS[1]}

		case "$command" in
			install | publish | source)
				case "$cur" in
					a*) COMPREPLY=( $( compgen -W 'authenticate' $cur ) ) ;;
					f*) COMPREPLY=( $( compgen -W 'force' $cur ) ) ;;
					 *) _default "authenticate force" ;;
				esac
			;;
			list)
				case "$cur" in
					s*) COMPREPLY=( $( compgen -W 'spacelet sandboxed' $cur ) ) ;;
					n*) COMPREPLY=( $( compgen -W 'native' $cur ) ) ;;
					v*) COMPREPLY=( $( compgen -W 'verbose' $cur ) ) ;;
					 *) _default "spacelet sandboxed native verbose" ;;
				esac
			;;
			help)
				case "$cur" in
					i*) COMPREPLY=( $( compgen -W 'install' $cur ) ) ;;
					p*) COMPREPLY=( $( compgen -W 'publish' $cur ) ) ;;
					s*) COMPREPLY=( $( compgen -W 'source start states stop' $cur ) ) ;;
					r*) COMPREPLY=( $( compgen -W 'remove restart register' $cur ) ) ;;
					l*) COMPREPLY=( $( compgen -W 'list' $cur ) ) ;;
					v*) COMPREPLY=( $( compgen -W 'version' $cur ) ) ;;
					 *) _default "install publish start stop remove restart source register states list version" ;;
				esac
			;;
		esac
	fi
}

#complete -F _spm -o filenames -o dirnames spm
complete -o default -F _spm -o filenames -o dirnames spm
