#!/bin/bash -e

# Source debconf library
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

# get all network adapter names
ADAPTERS=$(ifconfig -a | sed 's/[ \t\n].*//;/^\(lo\|\)$\|^mon/d')
ADAPTERS=$(echo "$ADAPTERS" | sed ':a;N;$!ba;s/\n/, /g')	# replace \n with ", "

db_subst spaceify/ethernet ADAPTERS "$ADAPTERS"				# replace names in debconf templates
db_subst spaceify/wlan ADAPTERS "$ADAPTERS"

# show questions every time the package is installed or reconfigured?
#db_fset spaceify/ethernet seen false
#db_fset spaceify/wlan seen false
#db_fset spaceify/wlan_ap seen false
#db_fset spaceify/admin_password seen false

# show questions in order and provide user the ability to back up
STATE=1
while [ $STATE -gt 0 -a $STATE -lt 5 ];
do
	case "$STATE" in
	1)
		db_input critical spaceify/ethernet || true
	;;

	2)
		db_input critical spaceify/wlan || true
	;;

	3)
		db_input critical spaceify/wlan_ap || true
	;;

	4)
		db_input critical spaceify/admin_password || true
	;;
	esac

	if db_go; then
		STATE=$(($STATE + 1))
	else
		STATE=$(($STATE - 1))
	fi
done
