#!/bin/bash

###########
# DEBCONF #
###########

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

echo PURGE | debconf-communicate spaceify > /dev/null 2>&1 || true

#############
# CONSTANTS #
#############

start_spaceify="# Added by spaceify"
end_spaceify="# Added by spaceify ends"
comm_out_spaceify="# Commented out by spaceify: "

###############################################################
# REMOVE SPACEIFY'S ENTRIES/COMMENTS FROM CONFIGURATION FILES #
###############################################################

#----- /etc/network/interfaces -----#

sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/network/interfaces

#----- /etc/default/docker -----#

sed -i "/${start_spaceify}/,/${end_spaceify}/d" /etc/default/docker

#----- /etc/rc.local -----#

sed -i "/${start_spaceify}/,/${end_spaceify}/d" /etc/rc.local

#----- /etc/sysctl.conf -----#

sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/sysctl.conf

#----- /etc/default/hostapd -----#

sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/default/hostapd

#----- /etc/monit/monitrc -----#

#sed -i "/${start_spaceify}/,/${end_spaceify}/d" /etc/monit/monitrc

# ----- /etc/dhcp/dhcpd.conf -----#

sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/dhcp/dhcpd.conf

###########################
# REMOVE SPACEIFY'S FILES #
###########################

service spaceify stop > /dev/null 2>&1 || true												# stop core first
service spaceifyipt stop > /dev/null 2>&1 || true
service spaceifydns stop > /dev/null 2>&1 || true

if [ "$1" = "remove" ]; then
	rm /etc/init/spaceify.conf > /dev/null 2>&1 || true
	rm /etc/init/spaceifydns.conf > /dev/null 2>&1 || true
	rm /etc/init/spaceifyipt.conf > /dev/null 2>&1 || true

	rm /etc/init.d/spaceify > /dev/null 2>&1 || true
	rm /etc/init.d/spaceifydns > /dev/null 2>&1 || true
	rm /etc/init.d/spaceifyipt > /dev/null 2>&1 || true

	rm -r /var/lib/spaceify/code > /dev/null 2>&1 || true
	rm -r /var/lib/spaceify/dev/iptpiper > /dev/null 2>&1 || true
	rm -r /var/lib/spaceify/dev/iptpipew > /dev/null 2>&1 || true
	printf "\n\nSpaceify's data stored in directory /var/lib/spaceify/data is not removed. Remove it by hand if necessary.\n\n"
fi

##########################################
# REMOVE SPACEIFY'S CHAINS FROM IPTABLES #
##########################################

iptables -t mangle -D PREROUTING -j Spaceify-mangle > /dev/null 2>&1 || true
iptables -t mangle -F Spaceify-mangle > /dev/null 2>&1 || true
iptables -t mangle -X Spaceify-mangle > /dev/null 2>&1 || true
iptables -t nat -D PREROUTING -m mark --mark 99 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.1 > /dev/null 2>&1 || true
iptables -t nat -D PREROUTING -m mark --mark 99 -p tcp --dport 443 -j DNAT --to-destination 10.0.0.1 > /dev/null 2>&1 || true
iptables -t filter -D FORWARD -m mark --mark 99 -j DROP > /dev/null 2>&1 || true

iptables -t nat -D PREROUTING -j Spaceify-HTTP-Nat-Redir > /dev/null 2>&1 || true
iptables -t nat -D POSTROUTING -j Spaceify-HTTP-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -F Spaceify-HTTP-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -X Spaceify-HTTP-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -F Spaceify-HTTP-Nat-Redir > /dev/null 2>&1 || true
iptables -t nat -X Spaceify-HTTP-Nat-Redir > /dev/null 2>&1 || true

iptables -t nat -D PREROUTING -j Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true
iptables -t nat -D POSTROUTING -j Spaceify-HTTPS-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -F Spaceify-HTTPS-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -X Spaceify-HTTPS-Nat-Masq > /dev/null 2>&1 || true
iptables -t nat -F Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true
iptables -t nat -X Spaceify-HTTPS-Nat-Redir > /dev/null 2>&1 || true

###########################
# REMOVE APPLICATION DATA #
###########################

conteiners=$(docker ps -a -q)																# Stop and remove all containers
if [[ "$conteiners" != "" ]]; then
	docker stop $(docker ps -a -q) --t=0 > /dev/null 2>&1 || true
	docker rm $(docker ps -a -q) > /dev/null 2>&1 || true
fi

#dbs="/var/lib/spaceify/data/db/spaceify.db"

#rows=$(sqlite3 $dbs -separator ";" "SELECT unique_name, unique_directory, docker_image_id, type FROM applications")
#splt=(${rows//$';'/ })

#iter=$((${#splt[@]} - 4))
#for i in $(seq 0 4 $iter); do
#
#	unique_name=${splt[$i]}
#	unique_directory=${splt[$(($i + 1))]}
#	docker_image_id=${splt[$(($i + 2))]}
#	type=${splt[$(($i + 3))]}
#
#	#$(sqlite3 $dbs "DELETE FROM applications WHERE unique_name='${unique_name}'")			# Delete database entries (for possible reinstall leave them undeleted)
#	#$(sqlite3 $dbs "DELETE FROM provided_services WHERE unique_name='${unique_name}'")
#	#$(sqlite3 $dbs "DELETE FROM inject_hostnames WHERE unique_name='${unique_name}'")
#	#$(sqlite3 $dbs "DELETE FROM inject_files WHERE unique_name='${unique_name}'")
#
#	docker rmi $docker_image_id  > /dev/null 2>&1 || true									# Remove application images
#
#	directory=""																			# Remove applications files but leave persistent volume untouched
#	if [[ "$type" == "spacelet" ]]; then
#		directory="/var/lib/spaceify/data/spacelets/${unique_directory}volume/"
#	elif [[ "$type" == "sandboxed" ]]; then
#		directory="/var/lib/spaceify/data/sandboxed/${unique_directory}volume/"
#	elif [[ "$type" == "native" ]]; then
#		directory="/var/lib/spaceify/data/native/${unique_directory}volume/"	
#	fi
#
#	rm -r "${directory}application" > /dev/null 2>&1 || true
#	rm -r "${directory}tls" > /dev/null 2>&1 || true
#
#done

#docker rmi spaceifyubuntu > /dev/null 2>&1 || true											# Remove Spaceify's images
